### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by ghost** [pomack/webmachine.go#1]
This library looks like a great start for webmachine on golang, but unfortunately a missing license basically means "all rights reserved". Would you mind adding a license, e.g. MIT?

For context, I used to be a co-maintainer of webmachine-ruby, and am now mostly coding golang.

**Comment by ghost** [comment]
> Would you mind adding a license, e.g. MIT?

Only if free-and-open-source is your intention! Of course I respect if it's not :) -- It's still good reading your code.

**Comment by pomack** [comment]
Added

**Comment by ghost** [comment]
Thanks! :100:
